"""initial_schema

Revision ID: 47e6d58c1724
Revises: 
Create Date: 2026-06-21 10:17:18.650468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e6d58c1724'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('action_label', sa.Text(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_travel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('accommodation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ticket_url', sa.Text(), nullable=True),
    sa.Column('ticket_file_url', sa.Text(), nullable=True),
    sa.Column('ticket_file_name', sa.Text(), nullable=True),
    sa.Column('ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('combined_ticket_url', sa.Text(), nullable=True),
    sa.Column('combined_ticket_name', sa.Text(), nullable=True),
    sa.Column('combined_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('arrival_airport_or_station', sa.Text(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('departure_airport_or_station', sa.Text(), nullable=True),
    sa.Column('flight_or_train_number', sa.Text(), nullable=True),
    sa.Column('pnr_number', sa.Text(), nullable=True),
    sa.Column('need_airport_to_hotel_cab', sa.Boolean(), nullable=True),
    sa.Column('need_hotel_to_airport_cab', sa.Boolean(), nullable=True),
    sa.Column('need_accommodation', sa.Boolean(), nullable=True),
    sa.Column('self_arranged_accommodation', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact_name', sa.Text(), nullable=True),
    sa.Column('emergency_contact_phone', sa.Text(), nullable=True),
    sa.Column('travel_status', sa.Enum('draft', 'submitted', 'verified', 'processing', 'completed', name='travel_status_enum'), nullable=True),
    sa.Column('travel_details_submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('travel_details_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('committee_notes', sa.Text(), nullable=True),
    sa.Column('accommodation_assigned', sa.Boolean(), nullable=True),
    sa.Column('hotel_name', sa.Text(), nullable=True),
    sa.Column('hotel_address', sa.Text(), nullable=True),
    sa.Column('hotel_room_number', sa.Text(), nullable=True),
    sa.Column('hotel_checkin_time', sa.Text(), nullable=True),
    sa.Column('cab_pickup_assigned', sa.Boolean(), nullable=True),
    sa.Column('cab_drop_assigned', sa.Boolean(), nullable=True),
    sa.Column('cab_driver_name', sa.Text(), nullable=True),
    sa.Column('cab_driver_phone', sa.Text(), nullable=True),
    sa.Column('participant_notes', sa.Text(), nullable=True),
    sa.Column('check_in_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('travel_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_reimbursement_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('account_holder_name', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('ifsc_code', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('branch_name', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('arrival_expense', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('return_expense', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_expense', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('receipts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.drop_index('ix_support_requests_id', table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_index('ix_chat_messages_room_id', table_name='chat_messages')
    op.drop_index('ix_chat_room_members_participant_id', table_name='chat_room_members')
    op.drop_index('ix_chat_rooms_event_id', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_team_id', table_name='chat_rooms')
    op.add_column('teams', sa.Column('is_qualified_round_3', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_qualified_round_3')
    op.create_index('ix_chat_rooms_team_id', 'chat_rooms', ['team_id'], unique=False)
    op.create_index('ix_chat_rooms_event_id', 'chat_rooms', ['event_id'], unique=False)
    op.create_index('ix_chat_room_members_participant_id', 'chat_room_members', ['participant_id'], unique=False)
    op.create_index('ix_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conflict_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notify_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='support_requests_pkey')
    )
    op.create_index('ix_support_requests_id', 'support_requests', ['id'], unique=False)
    op.drop_table('travel_reimbursement_claims')
    op.drop_table('travel_queries')
    op.drop_table('team_travel')
    op.drop_table('notifications')
    # ### end Alembic commands ###
